# The data sets to load and how to interpret them
data:
  data_set_1:
    path: /home/tec0/cfa-immunization-uptake-projection/data/NIS_2023-24.csv
    region_col: geography
    date_col: date
    estimate_col: estimate
    date_format: "%m/%d/%Y" # For example flu data, use "%m/%d/%Y %H:%M"
    rollout: 2023-09-01
    filters:
        geography: National
        group_name: Overall
        indicator: booster

# The timeframe over which to generate projections
timeframe:
  start: 2024-02-01
  end: 2024-04-30
  interval: 7d